version: '3.9'

services:
  api_web:
    build: ./api_web
    container_name: api_web_container
    ports:
      - "5000:5000"
    networks:
      - blur_net

  engine:
    build: ./engine
    container_name: engine_container
    ports:
      - "5001:5001"
    networks:
      - blur_net

networks:
  blur_net:
    driver: bridge
